#ifndef X
#include <seccomp.h>
#define X(int_arch, scmp_arch)
#define FALLBACK_X(int_arch)
#endif

X (ARCH_X86, SCMP_ARCH_X86)
X (ARCH_X86_64, SCMP_ARCH_X86_64)
X (ARCH_X32, SCMP_ARCH_X32)
X (ARCH_AARCH64, SCMP_ARCH_AARCH64)
X (ARCH_ARM, SCMP_ARCH_ARM)
#if SCMP_VER_MAJOR >= 2 && SCMP_VER_MINOR >= 6
X (ARCH_LOONGARCH64, SCMP_ARCH_LOONGARCH64)
X (ARCH_M68K, SCMP_ARCH_M68K)
X (ARCH_SH, SCMP_ARCH_SH)
X (ARCH_SHEB, SCMP_ARCH_SHEB)
#else
FALLBACK_X (ARCH_LOONGARCH64)
FALLBACK_X (ARCH_M68K)
FALLBACK_X (ARCH_SH)
FALLBACK_X (ARCH_SHEB)
#endif
X (ARCH_MIPSEL64N32, SCMP_ARCH_MIPSEL64N32)
X (ARCH_MIPSEL64, SCMP_ARCH_MIPSEL64)
X (ARCH_MIPSEL, SCMP_ARCH_MIPSEL)
X (ARCH_MIPS64N32, SCMP_ARCH_MIPS64N32)
X (ARCH_MIPS64, SCMP_ARCH_MIPS64)
X (ARCH_MIPS, SCMP_ARCH_MIPS)
X (ARCH_PARISC64, SCMP_ARCH_PARISC64)
X (ARCH_PARISC, SCMP_ARCH_PARISC)
X (ARCH_PPC64LE, SCMP_ARCH_PPC64LE)
X (ARCH_PPC64, SCMP_ARCH_PPC64)
X (ARCH_PPC, SCMP_ARCH_PPC)
X (ARCH_S390X, SCMP_ARCH_S390X)
X (ARCH_S390, SCMP_ARCH_S390)
X (ARCH_RISCV64, SCMP_ARCH_RISCV64)
