name: ubuntu-24.04 CI (clang)

on:
  push:

env:
  TERM: xterm-256color

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            asciidoctor \
            gettext \
            libbpf-dev \
            libelf-dev \
            libseccomp-dev \
            pkgconf \
            python3-pytest \
            zlib1g-dev \
            llvm \
            linux-tools-common \
            linux-tools-azure

      - name: Configure
        run: ./configure --devmode --prefix=/usr --destdir=build/inst

      - name: Make
        run: make -j$(nproc)

      - name: Make test
        run: make test -j$(nproc)

      - name: Test
        run: pytest test

      - name: Install
        run: make install

      - name: List files size
        run: (cd build/inst && tree --du -h .)
